### ISSUE TITLE
Question about transrate and use it

### ISSUE THREAD

**Issue by ISSuh** [karanpratapsingh/system-design#35]
First, thank you for your excellent resource. This resource is very helpful to me for study.

And I have a one question.
Can I translate your resource into korean and post it on my blog?

I think, given that this repository does not have a separate directory for the converted resources,
it seems that it does not want to have any content for the separate translated material.

So I ask you to check if it's okay to post it on my blog.
Of course, I will specify you and the original link of these repository.

**Comment by karanpratapsingh** [comment]
Hi @ISSuh Thank you, I am really glad you found this helpful.

Unfortunately, I cannot allow translation unless it's a **contribution to this repo first** since it's copyrighted material (CC-NC-ND 4.0), and a translation would be derivative which you won't be able to use.

I would love to have `translations/ko.md` contributed to this repo then feel free to link it/post it on your website.
